# Generated by Django 3.2.8 on 2021-10-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodecamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
